machines = {
  "master" => {"memory" => "700", "cpu" => "1", "image" => "bento/ubuntu-22.04"},
  "node01" => {"memory" => "700", "cpu" => "1", "image" => "bento/ubuntu-22.04"},
  "node02" => {"memory" => "700", "cpu" => "1", "image" => "bento/ubuntu-22.04"},
  "node03" => {"memory" => "700", "cpu" => "1", "image" => "bento/ubuntu-22.04"}
}

Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 300

  machines.each_with_index do |(name, conf), i|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      machine.vm.network "public_network"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]        
      end

      machine.vm.provision "shell", path: "instalar-docker.sh"

      if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end
